// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
  "swagger": "2.0",
  "info": {
    "description": "Microservice Gateway to LMS, HMS, BMS",
    "title": "API Hub",
    "contact": {},
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [],
  "paths": {
    "/login": {
      "post": {
        "description": "Returns JWT token if credentials are valid",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["auth"],
        "summary": "Login with username and password",
        "parameters": [
          {
            "description": "User credentials",
            "name": "credentials",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/models.User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          }
        }
      }
    },
    "/protected/lms": {
      "get": {
        "security": [{ "BearerAuth": [] }],
        "description": "Downloads data from external LMS API and saves to MongoDB",
        "produces": ["application/json"],
        "tags": ["lms"],
        "summary": "Fetch LMS data and store to MongoDB",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          }
        }
      }
    },
    "/protected/sftp": {
      "get": {
        "security": [{ "BearerAuth": [] }],
        "description": "Downloads a file from SFTP and displays its content",
        "produces": ["application/json"],
        "tags": ["sftp"],
        "summary": "Fetch file from SFTP and print contents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "models.User": {
      "type": "object",
      "properties": {
        "username": { "type": "string" },
        "password": { "type": "string" }
      }
    }
  },
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`

func init() {
	swag.Register("swagger", &swag.Spec{
		Version:          "1.0",
		Host:             "localhost:8080",
		BasePath:         "/",
		Schemes:          []string{},
		Title:            "API Hub",
		Description:      "Microservice Gateway to LMS, HMS, BMS",
		InfoInstanceName: "swagger",
		SwaggerTemplate:  docTemplate_swagger,
	})
}